### ISSUE TITLE
Specific badges aren't displayed, such as the Patreon badge, and CDB's mod badge

### ISSUE THREAD

**Issue by CDB-Man** [soulweaver91/anidb-user-scripts#17]
CDB's mod badge: https://anidb.net/up279512
Patreon badge: https://anidb.net/up560966

**Comment by CDB-Man** [comment]
Arokh's page works fine with current script: https://anidb.net/up47461
Komarex does not: https://anidb.net/up279512

**Comment by soulweaver91** [comment]
This seems to actually be a problem with parentheses used in the custom text, not the CDB badge itself; the presence of an opening parenthesis ends up breaking the parser that splits the tooltip into its components. (I guess I made the assumption that anything with a parentheses _must_ be a progressable badge which must follow a fixed format.) The Patreon badge for komarex also has text in parentheses, similarly breaking it.

(I guess that means I'll also have to make the Patreon badge to consider the tooltip text; most badges ignore the original name/text altogether while a select few, mostly the mod ones, copy that over.)
